#!/usr/bin/env python3
import argparse
from yaml import load, SafeLoader as Loader
from TeXcalendar import (
    BEGIN_DOCUMENT,
    END_DOCUMENT,
    NEWPAGE,
    preamble,
    get_dates,
    calendar
    )


parser = argparse.ArgumentParser(
    description="Read holidays from `holidays.yaml` and prints LaTeX calendar to stdout."
)
args = parser.parse_args()


with open("holidays.yaml", 'r') as hfile:
    holidays = load(hfile, Loader)

(start, end, hdays) = get_dates(holidays)

print("\n".join([
    preamble(hdays),
    BEGIN_DOCUMENT,
    calendar(start, end, "MTWRF"),
    NEWPAGE,
    calendar(start, end, "MW"),
    NEWPAGE,
    calendar(start, end, "TR"),
    END_DOCUMENT
]))
