#!/usr/bin/env python3

import canvas
import canvas_utils.course_conf as cnf
import argparse
import sys
from os import chdir, path

COURSEDIR = "~/Classes/"

parser = argparse.ArgumentParser(
    description="Upload a file to a course"
)
parser.add_argument('local_file', help="Local file to upload.")
parser.add_argument('--remote_path', default="",
                    help="Remote path to upload to. "
                    "Defaults to the course root.")
parser.add_argument('--course', default=None,
                    help="Course to upload to. "
                    "Defaults to current course when in a course directory.\n"
                    "Must be one of courses in {}.".format(COURSEDIR))
parser.add_argument('--section', dest="section", default=None,
                    help="The section to upload to.\n"
                    "Defaults to posting to all sections of the course."
                    "Must be one of the sections listed in the "
                    "course yaml file.")


args = parser.parse_args()

file = path.abspath(args.local_file)

canvas.read_access_token()

if args.course is not None:
    try:
        chdir(path.expanduser(COURSEDIR + args.course))
    except FileNotFoundError:
        print("Could not find course {}!".format(args.course))
        sys.exit(1)

try:
    config = cnf.get_course_config()
except FileNotFoundError:
    print("Cannot find a course config file.\n"
          "Perhaps you are not in a course directory?")
    sys.exit(1)


# try to find section:
if args.section is not None:
    sectionID = None
    for classid, classdata in config['sections'].items():
        if 'secnum' in classdata and classdata['secnum'] == args.section:
            sectionID = classid
            break
    if sectionID is None:
        print("Could not find section {}!".format(args.section))
        sys.exit(1)
    res = canvas.upload_file_to_course(classid, file,
                                       args.remote_path,
                                       overwrite=True)
    print(res)
else:  # post to all sections
    for classid in config['sections']:
        res = canvas.upload_file_to_course(classid, file,
                                           args.remote_path,
                                           overwrite=True)

        print(res)
